name: 'ethio_med_dwh'
version: '1.0.0'
config-version: 2

profile: 'ethio_med_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ethio_med_dwh:
    +materialized: view